spring:
    application:
        name: TRANSACTION-SERVICE
    datasource:
        url: jdbc:mysql://localhost:3306/transaction_db
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 8383

logging:
    file:
        name: logs/transaction.log

# Actuator Configuration
management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: health,info,metrics,env,beans,mappings,transaction-metrics

    endpoint:
        health:
            show-details: always
            show-components: always

    health:
        defaults:
            enabled: true

    info:
        env:
            enabled: true

# Configuration
build:
    version: "1.0"

transactions:
    message: "Welcome to MyBank transactions related REST APIs - UAT"
    contactDetails:
        name: "Laxman Jadhav"
        email: "laxman.jadhav@msedcl.in"
    onCallSupport:
        - 123123123
        - 4443332221
