spring.application.name=02_Employee_CRUD


server.port=8181
logging.file.name=logs/hello.log

spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.url=jdbc:mysql://localhost:3306/msedcldb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
