spring:
    application:
        name: CUSTOMER_SERVICE
    datasource:
        url: jdbc:mysql://localhost:3306/customer_db
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 8181

logging:
    file:
        name: logs/customer.log
