spring:
    application:
        name: TRANSACTION_SERVICE
    datasource:
        url: jdbc:mysql://localhost:3306/transaction_db
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 8383

logging:
    file:
        name: logs/transaction.log
